// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using segundoparcial_mtorres.DataLayer;

namespace DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("segundoparcial_mtorres.Entities.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("Episodes")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("segundoparcial_mtorres.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Young male hero focused on action, adventure and fighting.",
                            Title = "Shounen"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Isekai is a 'accidental travel' genre of light novels, manga, anime and video games that revolve around a normal person from Earth being transported to, reborn or otherwise trapped in a parallel universe, fantasy world or virtual world.",
                            Title = "Isekai"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Anime and manga in this category reflect the traditions of the Western genre. Westerns usually take place in the American Old West, but the genre has expanded to frontiers beyond, like space and future Japan.",
                            Title = "Western"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Aimed at demographic of young men between the ages of 15-24. Seinen anime and manga tend to be of a more violent and/or psychological nature than shonen series—though, of course, there are seinen comedies as well. They can also have content of a pornographic nature (though this is not the focus of the work).",
                            Title = "Seinen"
                        },
                        new
                        {
                            Id = 5,
                            Description = "“Shojo” (少女), which is often translated as “young girl,” is the female counterpart to shonen, and anime and manga of this type are aimed at girls between the ages of ten and eighteen. These tend to focus on romance and interpersonal relationships—though this does not mean they are necessarily without action or adventure.",
                            Title = "Shojo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Anime and manga of the “josei” (女性) variety are aimed at adult women. Josei series are often slice-of-life or romantic tales featuring adult women, though, in recent years, shonen-like action-adventures have become popular as well. In general, these works tend to contain more realistic interpersonal relationships (as opposed to shojo’s often idealized ones) and can cover darker subjects like rape and infidelity.",
                            Title = "Josei"
                        });
                });

            modelBuilder.Entity("segundoparcial_mtorres.Entities.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Chapters")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("ImageURL")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Manga");
                });

            modelBuilder.Entity("segundoparcial_mtorres.Entities.Anime", b =>
                {
                    b.HasOne("segundoparcial_mtorres.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("segundoparcial_mtorres.Entities.Manga", b =>
                {
                    b.HasOne("segundoparcial_mtorres.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
